ticho:
  datasource:
    url: jdbc:mysql://192.168.243.138:10032/ticho_intranet?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowMultiQueries=true
    username: ENC(8yUwi7gFsHhtfKcuEHa6Kg==)
    password: ENC(EMiOSD5Q5fe3ER0cP2BU70iZ5hM/OPeQ)
    driver-class-name: com.mysql.cj.jdbc.Driver
    log:
      enable: true
      print-sql: true
  security:
    ant-patterns:
      - /
      - /health
      - /**/user/token
      - /**/user/refreshToken
      - /doc.html
      - /swagger-resources/**
      - /webjars/**
      - /v2/api-docs
  cors:
    enable: true
  intranet:
    server:
      port: 5121
      sslEnable: false
      sslPort: 6443
      sslPath:
      sslPassword:
      maxRequests:
      maxBindPorts:
  log:
    enable: true
    print: true
  swagger:
    enable: false
